plugins {
    id "com.android.application"
}

android {
    namespace "uk.brimstone.simpletype"
    compileSdk 37

    defaultConfig {
        applicationId "uk.brimstone.simpletype"
        minSdk 29
        targetSdk 37
        versionCode 6
        versionName "0.1.5"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation "com.alphacephei:vosk-android:0.3.75"
}
